// a-voxel-engine — portable voxel engine entry point.
//
// SDL3 windowing/input + OpenGL renderer (3.3 core desktop, ES 3.0 Android)
// behind the portable Renderer interface. The world is generated by the
// deterministic TerrainGenerator through a frame-budgeted WorldGenerator
// queue, meshed by the exposed-face ChunkMesher, and uploaded to the renderer
// as per-chunk GPU meshes. The renderer can be swapped for a Vulkan backend
// later without touching this file's game-loop logic.

#include <SDL3/SDL.h>
#include <SDL3/SDL_main.h>

#include <glm/gtc/constants.hpp>
#include <glm/gtc/matrix_transform.hpp>
#include <glm/glm.hpp>

#include <algorithm>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <unordered_set>
#include <vector>

#include "mesh/builder.h"
#include "render/renderer.h"
#include "world/generator.h"
#include "world/world.h"

namespace {

// Orbit-camera state (drag to look, wheel to zoom). The camera orbits a fixed
// point above the spawn terrain.
double gYaw = 0.6;
double gPitch = 0.35;
double gDist = 20.0;
bool gDragging = false;

int gWindowWidth = 1280;
int gWindowHeight = 720;
bool gSuspended = false;  // minimized / (Android) backgrounded

glm::vec3 orbitOffset() {
    const float cy = static_cast<float>(std::cos(gPitch));
    const float sy = static_cast<float>(std::sin(gPitch));
    const float cyaw = static_cast<float>(std::cos(gYaw));
    const float syaw = static_cast<float>(std::sin(gYaw));
    return glm::vec3(gDist * cy * syaw, gDist * sy, gDist * cy * cyaw);
}

glm::mat4 buildViewProj(const glm::vec3& target) {
    const float aspect =
        (gWindowHeight > 0) ? static_cast<float>(gWindowWidth) /
                                  static_cast<float>(gWindowHeight)
                            : 1.0f;
    const glm::mat4 view =
        glm::lookAt(target + orbitOffset(), target, glm::vec3(0.0f, 1.0f, 0.0f));
    const glm::mat4 proj =
        glm::perspective(glm::radians(60.0f), aspect, 0.1f, 500.0f);
    return proj * view;
}

// Pack the mesher output into the renderer's upload format.
voxel::ChunkMeshData toMeshData(const voxel::mesh::ChunkMesh& mesh) {
    voxel::ChunkMeshData data;
    data.vertices = mesh.vertices.data();
    data.vertexCount = static_cast<std::uint32_t>(mesh.vertices.size());
    return data;
}

}  // namespace

int main(int argc, char* argv[]) {
    // Optional args: [maxFrames] [seed] (smoke-test / reproducible runs).
    long maxFrames = 0;
    if (argc >= 2) {
        maxFrames = std::atol(argv[1]);
    }
    std::uint32_t seed = 2024u;
    if (argc >= 3) {
        seed = static_cast<std::uint32_t>(std::strtoul(argv[2], nullptr, 0));
    }

    if (!SDL_Init(SDL_INIT_VIDEO | SDL_INIT_EVENTS)) {
        std::fprintf(stderr, "SDL_Init failed: %s\n", SDL_GetError());
        return 1;
    }

    // --- GL context hints (must be set before SDL_CreateWindow) ------------
    // Compatibility gate: desktop needs OpenGL 3.3 core, Android needs GLES 3.0.
#if defined(__ANDROID__)
    SDL_GL_SetAttribute(SDL_GL_CONTEXT_PROFILE_MASK, SDL_GL_CONTEXT_PROFILE_ES);
    SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION, 3);
    SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION, 0);
#else
    SDL_GL_SetAttribute(SDL_GL_CONTEXT_PROFILE_MASK, SDL_GL_CONTEXT_PROFILE_CORE);
    SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION, 3);
    SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION, 3);
#endif
    SDL_GL_SetAttribute(SDL_GL_DOUBLEBUFFER, 1);
    SDL_GL_SetAttribute(SDL_GL_DEPTH_SIZE, 24);
    SDL_GL_SetAttribute(SDL_GL_RED_SIZE, 8);
    SDL_GL_SetAttribute(SDL_GL_GREEN_SIZE, 8);
    SDL_GL_SetAttribute(SDL_GL_BLUE_SIZE, 8);
    SDL_GL_SetAttribute(SDL_GL_ALPHA_SIZE, 8);

    SDL_Window* window = SDL_CreateWindow(
        "a-voxel-engine", gWindowWidth, gWindowHeight,
        SDL_WINDOW_OPENGL | SDL_WINDOW_RESIZABLE);
    if (window == nullptr) {
        std::fprintf(stderr, "SDL_CreateWindow failed: %s\n", SDL_GetError());
        SDL_Quit();
        return 1;
    }

    int pixelW = 0, pixelH = 0;
    SDL_GetWindowSizeInPixels(window, &pixelW, &pixelH);
    gWindowWidth = pixelW;
    gWindowHeight = pixelH;

    voxel::RendererCreateInfo info;
    info.window = window;
    info.width = pixelW;
    info.height = pixelH;
    info.vsync = true;
    info.debug = false;

    auto renderer = voxel::createRenderer(voxel::RendererBackend::OpenGL, info);
    if (!renderer || !renderer->initialize()) {
        std::fprintf(stderr,
                     "Unsupported graphics: could not create an OpenGL context. "
                     "Desktop needs OpenGL 3.3+; Android needs OpenGL ES 3.0+.\n");
        SDL_DestroyWindow(window);
        SDL_Quit();
        return 1;
    }

    // --- World + generation + meshing --------------------------------------
    voxel::world::World world(seed);
    voxel::world::WorldGenerator generator(seed, world);
    voxel::mesh::ChunkMesher mesher;

    // Active chunk radius around the spawn column; terrain streams in over a
    // few seconds via the frame-budgeted queue.
    constexpr int kChunkRadius = 6;
    std::vector<voxel::world::ChunkCoord> activeChunks;
    activeChunks.reserve((2 * kChunkRadius + 1) * (2 * kChunkRadius + 1));
    for (int cx = -kChunkRadius; cx <= kChunkRadius; ++cx) {
        for (int cz = -kChunkRadius; cz <= kChunkRadius; ++cz) {
            activeChunks.push_back(voxel::world::ChunkCoord{cx, cz});
            generator.request(voxel::world::ChunkCoord{cx, cz});
        }
    }

    std::unordered_set<std::uint64_t> meshed;
    const auto uploadChunk = [&](voxel::world::ChunkCoord c) {
        voxel::world::Chunk* chunk = world.chunkAt(c);
        if (chunk == nullptr) {
            return;
        }
        voxel::mesh::ChunkMesh mesh;
        mesher.build(*chunk, c, world, mesh);
        renderer->uploadChunkMesh(c, toMeshData(mesh));
        chunk->clearDirty();
    };
    const auto uploadAllChunks = [&]() {
        for (const voxel::world::ChunkCoord c : activeChunks) {
            uploadChunk(c);
            meshed.insert(chunkKey(c));
        }
    };

    // Camera orbits a fixed point above the spawn surface.
    const float spawnY =
        std::max(generator.surfaceHeight(0, 0),
                 voxel::world::TerrainGenerator::kSeaLevel) +
        2.0f;
    const glm::vec3 cameraTarget(0.0f, spawnY, 0.0f);

    bool running = true;
    Uint64 prevTicks = SDL_GetTicks();
    long frameCount = 0;

    while (running) {
        SDL_Event event;
        while (SDL_PollEvent(&event)) {
            switch (event.type) {
                case SDL_EVENT_QUIT:
                    running = false;
                    break;

                case SDL_EVENT_KEY_DOWN:
                    if (event.key.key == SDLK_ESCAPE) {
                        running = false;
                    }
                    break;

                case SDL_EVENT_MOUSE_BUTTON_DOWN:
                    if (event.button.button == SDL_BUTTON_LEFT) {
                        gDragging = true;
                    }
                    break;
                case SDL_EVENT_MOUSE_BUTTON_UP:
                    if (event.button.button == SDL_BUTTON_LEFT) {
                        gDragging = false;
                    }
                    break;
                case SDL_EVENT_MOUSE_MOTION:
                    if (gDragging) {
                        gYaw -= event.motion.xrel * 0.01;
                        gPitch += event.motion.yrel * 0.01;
                        gPitch = std::clamp(gPitch, -1.2, 1.5);
                    }
                    break;
                case SDL_EVENT_MOUSE_WHEEL:
                    gDist *= (event.wheel.y > 0.0f) ? 0.9 : 1.1;
                    gDist = std::clamp(gDist, 4.0, 90.0);
                    break;

                case SDL_EVENT_WINDOW_PIXEL_SIZE_CHANGED:
                    gWindowWidth = event.window.data1;
                    gWindowHeight = event.window.data2;
                    renderer->onResize(gWindowWidth, gWindowHeight);
                    break;

                case SDL_EVENT_WINDOW_MINIMIZED:
                    gSuspended = true;
                    renderer->onPause();
                    break;
                case SDL_EVENT_WINDOW_RESTORED:
                    if (gSuspended) {
                        gSuspended = false;
                        renderer->onResume();
                        uploadAllChunks();  // GPU resources were rebuilt
                    }
                    break;
#if defined(__ANDROID__)
                case SDL_EVENT_WINDOW_FOCUS_LOST:
                    gSuspended = true;
                    renderer->onPause();
                    break;
                case SDL_EVENT_WINDOW_FOCUS_GAINED:
                    if (gSuspended) {
                        gSuspended = false;
                        renderer->onResume();
                        uploadAllChunks();
                    }
                    break;
#endif
                default:
                    break;
            }
        }

        const Uint64 now = SDL_GetTicks();
        const double deltaSeconds =
            static_cast<double>(now - prevTicks) / 1000.0;
        prevTicks = now;

        if (gSuspended) {
            SDL_Delay(16);
            continue;
        }

        // Stream generation and mesh upload (frame-budgeted, no stall).
        std::vector<voxel::world::ChunkCoord> generated;
        generator.tick(2, &generated);
        for (const voxel::world::ChunkCoord c : generated) {
            if (meshed.count(chunkKey(c)) != 0) {
                continue;
            }
            uploadChunk(c);
            meshed.insert(chunkKey(c));
        }

        if (renderer->beginFrame()) {
            voxel::RenderCamera camera;
            camera.viewProj = buildViewProj(cameraTarget);
            camera.eye = cameraTarget + orbitOffset();
            renderer->renderFrame(camera, deltaSeconds);
            renderer->endFrame();
        }

        ++frameCount;
        if (maxFrames > 0 && frameCount >= maxFrames) {
            running = false;
        }
    }

    renderer->shutdown();
    SDL_DestroyWindow(window);
    SDL_Quit();
    return 0;
}
