// a-voxel-engine — portable voxel engine entry point.
//
// SDL3 windowing/input + OpenGL renderer (3.3 core desktop, ES 3.0 Android)
// behind the portable Renderer interface. The world is generated by the
// deterministic TerrainGenerator through a frame-budgeted WorldGenerator
// queue, meshed by the exposed-face ChunkMesher, and uploaded to the renderer
// as per-chunk GPU meshes. The player flies through the world with a free-fly
// camera (WASD + Space/C, mouse look, wheel for speed) and per-axis voxel
// collision. The renderer can be swapped for a Vulkan backend later without
// touching this file's game-loop logic.

#include <SDL3/SDL.h>
#include <SDL3/SDL_main.h>

#include <glm/gtc/matrix_transform.hpp>
#include <glm/glm.hpp>

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <filesystem>
#include <string>
#include <unordered_set>
#include <vector>

#include "game/fly_camera.h"
#include "game/fly_collision.h"
#include "game/run_options.h"
#include "mesh/builder.h"
#include "render/renderer.h"
#include "world/generator.h"
#include "world/world.h"

namespace {

int gWindowWidth = 1280;
int gWindowHeight = 720;
bool gSuspended = false;  // minimized / (Android) backgrounded

voxel::game::FlyCamera gCam;
bool gMouseCaptured = false;  // desktop relative-mouse look
bool gDragging = false;       // Android / fallback drag look
float gFlySpeed = 16.0f;      // blocks/second (mouse wheel adjusts)

constexpr float kMinFlySpeed = 2.0f;
constexpr float kMaxFlySpeed = 200.0f;
constexpr float kDefaultFlySpeed = 16.0f;

struct Keys {
    bool w = false, a = false, s = false, d = false;
    bool space = false, c = false, shift = false;
};
Keys gKeys;

glm::mat4 buildViewProj() {
    const float aspect =
        (gWindowHeight > 0) ? static_cast<float>(gWindowWidth) /
                                  static_cast<float>(gWindowHeight)
                            : 1.0f;
    return glm::perspective(glm::radians(60.0f), aspect, 0.1f, 500.0f) *
           gCam.view();
}

void applyLook(float xrel, float yrel) {
    gCam.yaw += xrel * 0.0025f;
    gCam.pitch -= yrel * 0.0025f;  // mouse up -> look up
    gCam.pitch = std::clamp(gCam.pitch, -1.5f, 1.5f);
}

void refreshTitle(SDL_Window* window) {
    char title[128];
    std::snprintf(title, sizeof(title),
                  "a-voxel-engine  |  speed %3.0f blk/s  (Shift x4  |  wheel  |  R reset)",
                  gFlySpeed);
    SDL_SetWindowTitle(window, title);
}

// Pack the mesher output into the renderer's upload format.
voxel::ChunkMeshData toMeshData(const voxel::mesh::ChunkMesh& mesh) {
    voxel::ChunkMeshData data;
    data.vertices = mesh.vertices.data();
    data.vertexCount = static_cast<std::uint32_t>(mesh.vertices.size());
    return data;
}

}  // namespace

int main(int argc, char* argv[]) {
    voxel::game::RunOptions options;
    std::string optionsMessage;
    const voxel::game::ParseOptionsResult optionsResult =
        voxel::game::parseRunOptions(argc, argv, options, optionsMessage);
    if (optionsResult != voxel::game::ParseOptionsResult::Run) {
        std::FILE* stream = optionsResult == voxel::game::ParseOptionsResult::Help
                                ? stdout
                                : stderr;
        std::fprintf(stream, "%s%s", optionsMessage.c_str(),
                     optionsMessage.empty() || optionsMessage.back() == '\n' ? ""
                                                                           : "\n");
        return optionsResult == voxel::game::ParseOptionsResult::Help ? 0 : 2;
    }
    const long maxFrames = options.maxFrames;
    const std::uint32_t seed = options.seed;
    if (!options.screenshotDirectory.empty()) {
        std::error_code error;
        std::filesystem::create_directories(options.screenshotDirectory, error);
        if (error) {
            std::fprintf(stderr, "Could not create capture directory '%s': %s\n",
                         options.screenshotDirectory.c_str(), error.message().c_str());
            return 2;
        }
    }

    if (!SDL_Init(SDL_INIT_VIDEO | SDL_INIT_EVENTS)) {
        std::fprintf(stderr, "SDL_Init failed: %s\n", SDL_GetError());
        return 1;
    }

    // --- GL context hints (must be set before SDL_CreateWindow) ------------
    // Compatibility gate: desktop needs OpenGL 3.3 core, Android needs GLES 3.0.
#if defined(__ANDROID__)
    SDL_GL_SetAttribute(SDL_GL_CONTEXT_PROFILE_MASK, SDL_GL_CONTEXT_PROFILE_ES);
    SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION, 3);
    SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION, 0);
#else
    SDL_GL_SetAttribute(SDL_GL_CONTEXT_PROFILE_MASK, SDL_GL_CONTEXT_PROFILE_CORE);
    SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION, 3);
    SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION, 3);
#endif
    SDL_GL_SetAttribute(SDL_GL_DOUBLEBUFFER, 1);
    SDL_GL_SetAttribute(SDL_GL_DEPTH_SIZE, 24);
    SDL_GL_SetAttribute(SDL_GL_RED_SIZE, 8);
    SDL_GL_SetAttribute(SDL_GL_GREEN_SIZE, 8);
    SDL_GL_SetAttribute(SDL_GL_BLUE_SIZE, 8);
    SDL_GL_SetAttribute(SDL_GL_ALPHA_SIZE, 8);

    SDL_Window* window = SDL_CreateWindow(
        "a-voxel-engine", gWindowWidth, gWindowHeight,
        SDL_WINDOW_OPENGL | SDL_WINDOW_RESIZABLE);
    if (window == nullptr) {
        std::fprintf(stderr, "SDL_CreateWindow failed: %s\n", SDL_GetError());
        SDL_Quit();
        return 1;
    }

    int pixelW = 0, pixelH = 0;
    SDL_GetWindowSizeInPixels(window, &pixelW, &pixelH);
    gWindowWidth = pixelW;
    gWindowHeight = pixelH;

    voxel::RendererCreateInfo info;
    info.window = window;
    info.width = pixelW;
    info.height = pixelH;
    info.vsync = true;
    info.debug = false;

    auto renderer = voxel::createRenderer(voxel::RendererBackend::OpenGL, info);
    if (!renderer || !renderer->initialize()) {
        std::fprintf(stderr,
                     "Unsupported graphics: could not create an OpenGL context. "
                     "Desktop needs OpenGL 3.3+; Android needs OpenGL ES 3.0+.\n");
        SDL_DestroyWindow(window);
        SDL_Quit();
        return 1;
    }

    // --- World + generation + meshing --------------------------------------
    voxel::world::World world(seed);
    voxel::world::WorldGenerator generator(world);
    voxel::mesh::ChunkMesher mesher;

    std::unordered_set<std::uint64_t> meshed;
    const auto uploadChunk = [&](voxel::world::ChunkCoord c) {
        voxel::world::Chunk* chunk = world.chunkAt(c);
        if (chunk == nullptr) {
            return;
        }
        voxel::mesh::ChunkMesh mesh;
        mesher.build(*chunk, c, world, mesh);
        renderer->uploadChunkMesh(c, toMeshData(mesh));
        chunk->clearDirty();
    };
    const auto uploadAllChunks = [&]() {
        for (const voxel::world::ChunkCoord c : world.chunkCoords()) {
            uploadChunk(c);
            meshed.insert(chunkKey(c));
        }
    };
    constexpr voxel::world::Coord kNeighborOffsets[4][2] = {
        {-1, 0}, {1, 0}, {0, -1}, {0, 1}};
    const auto remeshLoadedNeighbors = [&](voxel::world::ChunkCoord center) {
        for (const auto& offset : kNeighborOffsets) {
            const voxel::world::ChunkCoord neighbor{
                center.cx + offset[0], center.cz + offset[1]};
            if (world.chunkAt(neighbor) == nullptr) {
                continue;
            }
            uploadChunk(neighbor);
            meshed.insert(chunkKey(neighbor));
        }
    };

    // Spawn the camera above the spawn terrain, looking back toward origin.
    const float spawnY =
        std::max(generator.surfaceHeight(0, 0),
                 voxel::world::TerrainGenerator::kSeaLevel) +
        2.0f;
    gCam.position = glm::vec3(0.0f, spawnY + 6.0f, -12.0f);
    gCam.yaw = 0.0f;
    gCam.pitch = -0.15f;
    refreshTitle(window);

#if !defined(__ANDROID__)
    gMouseCaptured = SDL_SetWindowRelativeMouseMode(window, true);
#endif

    bool running = true;
    bool screenshotCaptured = false;
    bool screenshotFailed = false;
    Uint64 prevTicks = SDL_GetTicks();
    long frameCount = 0;

    while (running) {
        SDL_Event event;
        while (SDL_PollEvent(&event)) {
            switch (event.type) {
                case SDL_EVENT_QUIT:
                    running = false;
                    break;

                case SDL_EVENT_KEY_DOWN:
                    switch (event.key.key) {
                        case SDLK_ESCAPE:
                            running = false;
                            break;
                        case SDLK_W:
                            gKeys.w = true;
                            break;
                        case SDLK_A:
                            gKeys.a = true;
                            break;
                        case SDLK_S:
                            gKeys.s = true;
                            break;
                        case SDLK_D:
                            gKeys.d = true;
                            break;
                        case SDLK_SPACE:
                            gKeys.space = true;
                            break;
                        case SDLK_C:
                            gKeys.c = true;
                            break;
                        case SDLK_LSHIFT:
                        case SDLK_RSHIFT:
                            gKeys.shift = true;
                            break;
                        case SDLK_R:
                            gFlySpeed = kDefaultFlySpeed;
                            refreshTitle(window);
                            break;
                        default:
                            break;
                    }
                    break;
                case SDL_EVENT_KEY_UP:
                    switch (event.key.key) {
                        case SDLK_W:
                            gKeys.w = false;
                            break;
                        case SDLK_A:
                            gKeys.a = false;
                            break;
                        case SDLK_S:
                            gKeys.s = false;
                            break;
                        case SDLK_D:
                            gKeys.d = false;
                            break;
                        case SDLK_SPACE:
                            gKeys.space = false;
                            break;
                        case SDLK_C:
                            gKeys.c = false;
                            break;
                        case SDLK_LSHIFT:
                        case SDLK_RSHIFT:
                            gKeys.shift = false;
                            break;
                        default:
                            break;
                    }
                    break;

                case SDL_EVENT_MOUSE_BUTTON_DOWN:
                    if (event.button.button == SDL_BUTTON_LEFT) {
                        gDragging = true;
                    }
                    break;
                case SDL_EVENT_MOUSE_BUTTON_UP:
                    if (event.button.button == SDL_BUTTON_LEFT) {
                        gDragging = false;
                    }
                    break;
                case SDL_EVENT_MOUSE_MOTION:
                    if (gMouseCaptured || gDragging) {
                        applyLook(event.motion.xrel, event.motion.yrel);
                    }
                    break;
                case SDL_EVENT_MOUSE_WHEEL:
                    gFlySpeed *= (event.wheel.y > 0.0f) ? 1.5f : 0.667f;
                    gFlySpeed =
                        std::clamp(gFlySpeed, kMinFlySpeed, kMaxFlySpeed);
                    refreshTitle(window);
                    break;

                case SDL_EVENT_WINDOW_PIXEL_SIZE_CHANGED:
                    gWindowWidth = event.window.data1;
                    gWindowHeight = event.window.data2;
                    renderer->onResize(gWindowWidth, gWindowHeight);
                    break;

                case SDL_EVENT_WINDOW_MINIMIZED:
                    gSuspended = true;
                    renderer->onPause();
                    break;
                case SDL_EVENT_WINDOW_RESTORED:
                    if (gSuspended) {
                        gSuspended = false;
                        renderer->onResume();
                        uploadAllChunks();  // GPU resources were rebuilt
                    }
                    break;
#if defined(__ANDROID__)
                case SDL_EVENT_WINDOW_FOCUS_LOST:
                    gSuspended = true;
                    renderer->onPause();
                    break;
                case SDL_EVENT_WINDOW_FOCUS_GAINED:
                    if (gSuspended) {
                        gSuspended = false;
                        renderer->onResume();
                        uploadAllChunks();
                    }
                    break;
#endif
                default:
                    break;
            }
        }

        const Uint64 now = SDL_GetTicks();
        const double deltaSeconds =
            static_cast<double>(now - prevTicks) / 1000.0;
        prevTicks = now;

        if (gSuspended) {
            SDL_Delay(16);
            continue;
        }

        // --- Fly movement (per-axis voxel collision) ------------------------
        const float dt = std::min(static_cast<float>(deltaSeconds), 0.05f);
        const float speed = gFlySpeed * (gKeys.shift ? 4.0f : 1.0f);

        glm::vec3 wish(0.0f);
        if (gKeys.w) {
            wish += gCam.horizontalForward();
        }
        if (gKeys.s) {
            wish -= gCam.horizontalForward();
        }
        if (gKeys.d) {
            wish += gCam.right();
        }
        if (gKeys.a) {
            wish -= gCam.right();
        }
        glm::vec3 horiz(0.0f);
        if (glm::length(wish) > 1e-6f) {
            horiz = glm::normalize(wish) * (speed * dt);
        }
        const float vy =
            ((gKeys.space ? 1.0f : 0.0f) - (gKeys.c ? 1.0f : 0.0f)) *
            speed * dt;

        voxel::game::moveFlyAxis(world, gCam.position, 0, horiz.x);
        voxel::game::moveFlyAxis(world, gCam.position, 2, horiz.z);
        voxel::game::moveFlyAxis(world, gCam.position, 1, vy);

        // --- Stream generation around the camera -----------------------------
        constexpr std::uint32_t kLoadRadius = 6;
        constexpr std::uint32_t kUnloadRadius = 8;
        const voxel::world::ChunkCoord camChunk = voxel::world::chunkCoordOf(
            voxel::world::WorldPosition{
                static_cast<voxel::world::Coord>(std::floor(gCam.position.x)),
                0,
                static_cast<voxel::world::Coord>(std::floor(gCam.position.z))});
        generator.setPriorityCenter(camChunk);
        generator.cancelOutside(camChunk, kLoadRadius);
        for (int cx = -static_cast<int>(kLoadRadius);
             cx <= static_cast<int>(kLoadRadius); ++cx) {
            for (int cz = -static_cast<int>(kLoadRadius);
                 cz <= static_cast<int>(kLoadRadius); ++cz) {
                generator.request(
                    voxel::world::ChunkCoord{camChunk.cx + cx, camChunk.cz + cz});
            }
        }

        // Retain a two-chunk hysteresis band so crossing a chunk boundary does
        // not immediately destroy and recreate the same CPU/GPU resources.
        std::vector<voxel::world::ChunkCoord> unload;
        for (const voxel::world::ChunkCoord c : world.chunkCoords()) {
            const std::int64_t dx =
                std::abs(static_cast<std::int64_t>(c.cx) - camChunk.cx);
            const std::int64_t dz =
                std::abs(static_cast<std::int64_t>(c.cz) - camChunk.cz);
            if (dx > kUnloadRadius || dz > kUnloadRadius) {
                unload.push_back(c);
            }
        }
        for (const voxel::world::ChunkCoord c : unload) {
            world.unloadChunk(c);
            renderer->clearChunkMesh(c);
            meshed.erase(chunkKey(c));
            // The surviving boundary chunks must expose faces that were
            // previously hidden by the removed neighbor.
            remeshLoadedNeighbors(c);
        }

        std::vector<voxel::world::ChunkCoord> generated;
        generator.tick(4, &generated);
        for (const voxel::world::ChunkCoord c : generated) {
            if (meshed.count(chunkKey(c)) != 0) {
                continue;
            }
            uploadChunk(c);
            meshed.insert(chunkKey(c));
            // Older chunks may have emitted temporary faces against the then
            // missing chunk. Rebuild them now that their neighbor exists.
            remeshLoadedNeighbors(c);
        }

        if (renderer->beginFrame()) {
            voxel::RenderCamera camera;
            camera.viewProj = buildViewProj();
            camera.eye = gCam.position;
            renderer->renderFrame(camera, deltaSeconds);
            if (!options.screenshotPath.empty() &&
                frameCount + 1 == options.screenshotFrame) {
                if (!renderer->captureScreenshot(options.screenshotPath)) {
                    screenshotFailed = true;
                } else {
                    screenshotCaptured = true;
                }
                // Capture scenarios are intentionally bounded and
                // reproducible; do not keep simulating after their frame.
                running = false;
            }
            if (!options.screenshotDirectory.empty() &&
                (frameCount + 1) % options.screenshotInterval == 0) {
                char filename[64];
                std::snprintf(filename, sizeof(filename), "frame-%06ld.png",
                              frameCount + 1);
                const std::filesystem::path output =
                    std::filesystem::path(options.screenshotDirectory) / filename;
                if (!renderer->captureScreenshot(output.string())) {
                    screenshotFailed = true;
                    running = false;
                } else {
                    screenshotCaptured = true;
                }
            }
            renderer->endFrame();
        }

        ++frameCount;
        if (maxFrames > 0 && frameCount >= maxFrames) {
            running = false;
        }
    }

    renderer->shutdown();
    SDL_DestroyWindow(window);
    SDL_Quit();
    return screenshotFailed ||
                   (!options.screenshotPath.empty() && !screenshotCaptured)
               ? 1
               : 0;
}
